INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
ERROR:telegram.ext._application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "E:\python\Lib\site-packages\telegram\ext\_application.py", line 945, in process_update
    await coroutine
  File "E:\python\Lib\site-packages\telegram\ext\_handler.py", line 135, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\telegram_bot\main.py", line 40, in planet
    await update.message.reply_text(constellation)
                                    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'constellation' where it is not associated with a value
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
ERROR:telegram.ext._application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "E:\python\Lib\site-packages\telegram\ext\_application.py", line 945, in process_update
    await coroutine
  File "E:\python\Lib\site-packages\telegram\ext\_handler.py", line 135, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\telegram_bot\main.py", line 35, in planet
    result = ephem.Earth('2023/02/13')
             ^^^^^^^^^^^
AttributeError: module 'ephem' has no attribute 'Earth'
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
ERROR:telegram.ext._application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "E:\python\Lib\site-packages\telegram\ext\_application.py", line 945, in process_update
    await coroutine
  File "E:\python\Lib\site-packages\telegram\ext\_handler.py", line 135, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\telegram_bot\main.py", line 48, in planet
    constellation = ephem.constellation(result)
                                        ^^^^^^
UnboundLocalError: cannot access local variable 'result' where it is not associated with a value
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
INFO:root:Бот стартовал
INFO:apscheduler.scheduler:Scheduler started
INFO:telegram.ext._application:Application started
INFO:telegram.ext._application:Application is stopping. This might take a moment.
INFO:apscheduler.scheduler:Scheduler has been shut down
INFO:telegram.ext._application:Application.stop() complete
